import matplotlib as mpl
import matplotlib.pyplot as plt

mpl.rc("axes", labelsize=14)
mpl.rc("xtick", labelsize=12)
mpl.rc("ytick", labelsize=12)
plt.xlabel("r")
plt.ylabel("percentage of connected graphs")
plt.title("Percentage of connected graphs vs r")

# Plot the data generated by main.cpp
with open("out.txt") as f:
    for line in f:
        r, p = map(float, line.split())
        plt.plot(r, p * 100, "ko")

plt.savefig("render.png")
plt.show()
